CREATE TABLE DIRECCION(
	ID_DIRECCION NUMBER(22) PRIMARY KEY,
	CALLE VARCHAR2(60) NOT NULL,
	NUMERO NUMBER(22) NOT NULL,
	PISO VARCHAR2(20) NOT NULL,
	CIUDAD VARCHAR2(20) NOT NULL
);

CREATE TABLE CODPOSTAL(
	CALLE VARCHAR2(60),
	CIUDAD VARCHAR2(20),
	CODPOSTAL NUMBER(22) NOT NULL,
PRIMARY KEY (CALLE, CIUDAD)
);

CREATE TABLE TITULAR(
	DNI VARCHAR2(9) PRIMARY KEY,
	NOMBRE VARCHAR2(50) NOT NULL,
	APELLIDO1 VARCHAR2(25) NOT NULL,
	APELLIDO2 VARCHAR2(25),
	DIRECCION VARCHAR2(22) NOT NULL,
	TELEFONO VARCHAR2(11) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
FOREIGN KEY (DIRECCION) REFERENCES DIRECCION(ID_DIRECCION)
);

CREATE TABLE SUCURSAL(
	CODOFICINA NUMBER(22) PRIMARY KEY,
	DIR CHAR(50) NOT NULL,
	TFNO NUMBER(22) NOT NULL
);

CREATE TABLE CODENTIDADES(
	BANCO VARCHAR2(20) PRIMARY KEY,
	CODIGO VARCHAR2(50) NOT NULL
);

CREATE TABLE CUENTA(
	CCC CHAR(20),
	SALDO NUMBER(22) NOT NULL,
	FECHACREACION DATE NOT NULL,
	TITULAR VARCHAR2(9) NOT NULL,
PRIMARY KEY(CCC),
FOREIGN KEY (TITULAR) REFERENCES TITULAR(DNI)
);

CREATE TABLE CUENTAAHORRO(
	CCC CHAR(20) PRIMARY KEY,
	TIPOINTERES NUMBER(22) NOT NULL,
	FOREIGN KEY (CCC) REFERENCES CUENTA(CCC)
);

CREATE TABLE CUENTACORRIENTE(
	CCC(20) PRIMARY KEY,
	SUCURSAL_CODOFICINA NUMBER(22),
FOREIGN KEY (CCC) REFERENCES CUENTA(CCC),
FOREIGN KEY (SUCURSAL_CODOFICINA) REFERENCES SUCURSAL(CODOFICINA)
);

CREATE TABLE OPERACION(
	NUMOP NUMBER(22),
	DESCRIPCIONOP CHAR(50),
	FECHAOP DATE,
	HORAO CHAR(5),
	CANTIDADOP NUMBER(22) NOT NULL,
	CCC CHAR(20)
PRIMARY KEY(NUMOP, CCC),
FOREIGN KEY (CCC) REFERENCES CUENTA(CCC)
);

CREATE TABLE OPTRANSFERENCIA(
	NUMOP NUMBER(22),
	CUENTADESTINO CHAR(20) NOT NULL,
	CCC CHAR(20),
PRIMARY KEY(NUMOP, CCC),
FOREIGN KEY (CCC) REFERENCES CUENTA(CCC),
FOREIGN KEY (NUMOP) REFERENCES OPERACION(NUMOP)
);

CREATE TABLE OPEFECTIVO(
	NUMOP NUMBER(22),
	TIPOOPEFECTIVO CHAR(8) NOT NULL,
	SUCURSAL_CODOFICINA NUMBER(22) NOT NULL,
	CCC CHAR(20),
PRIMARY KEY(NUMOP, CCC),
FOREIGN KEY (NUMOP) REFERENCES OPERACION(NUMOP),
FOREIGN KEY (CCC) REFERENCES CUENTA(CCC)
);
